"""empty message

Revision ID: 0aad829683a5
Revises: 1012f80e8f65
Create Date: 2019-06-19 22:14:04.589969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0aad829683a5'
down_revision = '1012f80e8f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('company', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('from_date', sa.String(length=80), nullable=True),
    sa.Column('to_date', sa.String(length=80), nullable=True),
    sa.Column('resume', sa.String(length=80), nullable=True),
    sa.Column('page', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('about', 'description',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('about', 'page',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('about', 'resume',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('about', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('product', 'date',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('product', 'description',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('product', 'page',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('product', 'url',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('product', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user', 'dobDate',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'firstname',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'imageURL',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'lastname',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True)
    op.alter_column('user', 'resumeStyle',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'theme',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'title',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'title',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'theme',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'resumeStyle',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False)
    op.alter_column('user', 'lastname',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'imageURL',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'firstname',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'dobDate',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('product', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('product', 'url',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('product', 'page',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('product', 'description',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('product', 'date',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('about', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('about', 'resume',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('about', 'page',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.alter_column('about', 'description',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.drop_table('experience')
    # ### end Alembic commands ###
