"""empty message

Revision ID: 0ce75cb8c39b
Revises: 0aad829683a5
Create Date: 2019-06-20 14:39:51.028368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ce75cb8c39b'
down_revision = '0aad829683a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('fromDate', sa.String(length=80), nullable=True))
    op.add_column('experience', sa.Column('toDate', sa.String(length=80), nullable=True))
    op.drop_column('experience', 'from_date')
    op.drop_column('experience', 'to_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('to_date', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('experience', sa.Column('from_date', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('experience', 'toDate')
    op.drop_column('experience', 'fromDate')
    # ### end Alembic commands ###
