"""empty message

Revision ID: 7b14e3f8a2dd
Revises: b9cb0f88be69
Create Date: 2019-06-19 16:47:53.366009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b14e3f8a2dd'
down_revision = 'b9cb0f88be69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('date', table_name='product')
    op.drop_index('description', table_name='product')
    op.drop_index('page', table_name='product')
    op.drop_index('url', table_name='product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('url', 'product', ['url'], unique=True)
    op.create_index('page', 'product', ['page'], unique=True)
    op.create_index('description', 'product', ['description'], unique=True)
    op.create_index('date', 'product', ['date'], unique=True)
    # ### end Alembic commands ###
