"""empty message

Revision ID: a28184e99121
Revises: 
Create Date: 2019-06-18 19:03:09.739691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28184e99121'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=12), nullable=False),
    sa.Column('dobDate', sa.String(length=10), nullable=False),
    sa.Column('imageURL', sa.String(length=120), nullable=False),
    sa.Column('resumeStyle', sa.String(length=120), nullable=False),
    sa.Column('theme', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dobDate'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firstname'),
    sa.UniqueConstraint('imageURL'),
    sa.UniqueConstraint('lastname'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('resumeStyle'),
    sa.UniqueConstraint('theme'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
